apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-srv
  # annotations is going to tell ingress that it has some routing rules to be configured
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  # rules is used to specify specific routing rules
  rules:
    - host: posts.com
      http:
        paths:
          - path: /posts
            backend:
              serviceName: posts-clusterip-srv
              servicePort: 4000
